name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      # Install dependencies and build
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm build
        env:
          NODE_ENV: production

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # or your AWS region

      # Sync to S3 Bucket
      - name: Sync to S3
        run: |
          aws s3 sync frontend/build s3://${{ secrets.AWS_S3_BUCKET }} --no-progress --delete
          # Add any additional flags you need for the aws s3 sync command